version: "3.7" 

services:
  curl-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - ZONE_ID=${ZONE_ID}
      - RECORD_ID=${RECORD_ID}
      - EMAIL=${EMAIL}
      - AUTH_KEY=${AUTH_KEY}
      - CUR_IP=${CUR_IP}
      - CUR_IPV6=${CUR_IPV6}
      - DEBUG=${DEBUG}
    networks:
      - ipv6net

networks:
  ipv6net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "2403:6200:8857:c01b::/64"
